Add support for x86_64-fortanix-unknown-sgx target
akash-fortanix/time pull request #1
Opened 2018-12-11 13:47 UTC by akash-fortanix

2018-12-11 13:55 UTC, jethrogb requested changes

2018-12-11 13:55 UTC, jethrogb commented on src/sys.rs
> +    pub fn get_time() -> (i64, i32) {
Write this in terms of `SteadyTime::new`

2018-12-11 13:55 UTC, jethrogb commented on src/sys.rs
> +            Ok(n) => n.as_nanos() as u64,
This function is not stable, compute manually instead from `SystemTime::now()`

2018-12-11 13:55 UTC, jethrogb commented on src/sys.rs
> +                Err(_) => panic!("SystemTime before UNIX EPOCH!"),
Use `unwrap` for error handling, add comments explaining why `unwrap` is ok

2018-12-11 13:55 UTC, jethrogb commented on src/sys.rs
> +        fn sub(self, _other: SteadyTime) -> Duration {
Remove `_` prefix

2018-12-11 14:57 UTC, jethrogb commented on src/duration.rs
> +    pub fn raw(&self) -> (i64, i32) {
Should be `pub(crate)`

2018-12-11 14:58 UTC, jethrogb commented on src/sys.rs
> +        duration.0 as u64 * NANOS_PER_SEC + duration.1 as u64
This is fine. My original suggestion was to do this one in terms of `SystemTime`, not `SteadyTime`, that would save you a signed-unsigned conversion.

2018-12-12 00:58 UTC, akash-fortanix commented
filed PR against original repo, the purpose of this PR is served

2018-12-12 00:58 UTC, closed without merging